# old

# image_width: 1280
# image_height: 1024
# camera_name: narrow_stereo
# camera_matrix:
#   rows: 3
#   cols: 3
#   data: [1560.46759,    0.     ,  627.94252,
#             0.     , 1563.0218 ,  519.00352,
#             0.     ,    0.     ,    1.     ]
# distortion_model: plumb_bob
# distortion_coefficients:
#   rows: 1
#   cols: 5
#   data: [-0.059454, 0.136857, -0.000134, 0.001950, 0.000000]
# rectification_matrix:
#   rows: 3
#   cols: 3
#   data: [1., 0., 0.,
#          0., 1., 0.,
#          0., 0., 1.]
# projection_matrix:
#   rows: 3
#   cols: 4
#   data: [1550.59436,    0.     ,  629.28898,    0.     ,
#             0.     , 1554.92236,  518.36577,    0.     ,
#             0.     ,    0.     ,    1.     ,    0.     ]

# 12mm hero

image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [2969.93015,    0.     ,  628.4726 ,
            0.     , 2967.94543,  507.14551,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.072582, 0.422508, -0.001299, -0.003165, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2960.41748,    0.     ,  626.56375,    0.     ,
            0.     , 2960.53491,  506.23922,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]