#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

export WEBOTS_TARGET_LATERAL_ENABLED="${WEBOTS_TARGET_LATERAL_ENABLED:-true}"
export WEBOTS_TARGET_LATERAL_AXIS="${WEBOTS_TARGET_LATERAL_AXIS:-y}"
export WEBOTS_TARGET_LATERAL_AMPLITUDE="${WEBOTS_TARGET_LATERAL_AMPLITUDE:-1.5}"
export WEBOTS_TARGET_LATERAL_SPEED="${WEBOTS_TARGET_LATERAL_SPEED:-1.0}"
export WEBOTS_TARGET_LATERAL_ACCEL="${WEBOTS_TARGET_LATERAL_ACCEL:-3.0}"
export WEBOTS_TARGET_LATERAL_DECEL="${WEBOTS_TARGET_LATERAL_DECEL:-3.0}"
export WEBOTS_TARGET_LATERAL_INITIAL_DIRECTION="${WEBOTS_TARGET_LATERAL_INITIAL_DIRECTION:-1.0}"

exec "${SCRIPT_DIR}/run_stationary_spin_target_test.sh" "$@"
