image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [2524.86797,    0.     ,  624.57587,
            0.     , 2523.637  ,  598.94011,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.046998, 0.212674, 0.007242, -0.003115, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2522.33179,    0.     ,  622.33748,    0.     ,
            0.     , 2516.31787,  601.4118 ,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
