/**:
  ros__parameters:
    image_topic: "/image_raw"
    rune_topic: "/rune_target"
    runes_topic: "/rune_targets"
    result_img_topic: "/auto_buff/debug/result_img"
    result_img_compressed_topic: "/auto_buff/debug/result_img/compressed"
    is_big_rune: true
    debug_view: false
    debug_jpeg_quality: 70
    min_confidence: 0.35
    device: "CPU"
    use_latency_performance_mode: true
    top_k: 30
    nms_threshold: 0.45
    merge_conf_error: 0.2
    merge_min_iou: 0.85
