version: 1

model_labels:
  - class_id: 0
    model_label: "B1"
    color: "blue"
    publish_number: "1"
    publish_type: "large"
  - class_id: 1
    model_label: "B2"
    color: "blue"
    publish_number: "2"
    publish_type: "small"
  - class_id: 2
    model_label: "B3"
    color: "blue"
    publish_number: "3"
    publish_type: "small"
  - class_id: 3
    model_label: "B4"
    color: "blue"
    publish_number: "4"
    publish_type: "small"
  - class_id: 4
    model_label: "B5"
    color: "blue"
    publish_number: "5"
    publish_type: "small"
  - class_id: 5
    model_label: "BO"
    color: "blue"
    publish_number: "outpost"
    publish_type: "small"
  - class_id: 6
    model_label: "BS"
    color: "blue"
    publish_number: "sentry"
    publish_type: "small"
  - class_id: 7
    model_label: "R1"
    color: "red"
    publish_number: "1"
    publish_type: "large"
  - class_id: 8
    model_label: "R2"
    color: "red"
    publish_number: "2"
    publish_type: "small"
  - class_id: 9
    model_label: "R3"
    color: "red"
    publish_number: "3"
    publish_type: "small"
  - class_id: 10
    model_label: "R4"
    color: "red"
    publish_number: "4"
    publish_type: "small"
  - class_id: 11
    model_label: "R5"
    color: "red"
    publish_number: "5"
    publish_type: "small"
  - class_id: 12
    model_label: "RO"
    color: "red"
    publish_number: "outpost"
    publish_type: "small"
  - class_id: 13
    model_label: "RS"
    color: "red"
    publish_number: "sentry"
    publish_type: "small"

ignore_labels: []
