image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [2584.56115,    0.     ,  645.56631,
            0.     , 2586.96697,  510.5751 ,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.049738, 0.322367, 0.002420, -0.000493, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2580.5481 ,    0.     ,  644.76784,    0.     ,
            0.     , 2581.64844,  511.00166,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
