image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [2405.73878,    0.     ,  524.56303,
            0.     , 2403.09056,  497.05077,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.049053, 0.286918, 0.003764, -0.000043, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2406.13079,    0.     ,  524.85084,    0.     ,
            0.     , 2402.26677,  498.84583,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
