image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1556.34704,    0.     ,  610.59754,
            0.     , 1557.43488,  503.80001,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.088389, 0.184307, -0.001816, 0.000173, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1541.14038,    0.     ,  610.38965,    0.     ,
            0.     , 1544.15491,  502.2795 ,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
